"""Crop and Disease Class Definitions, Vernacular Names, and Pathogen Meta."""

DISEASE_CLASSES = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy"
]

DISEASE_METADATA = {
    "Tomato___Early_blight": {
        "crop": "Tomato",
        "crop_hi": "टमाटर",
        "crop_pa": "ਟਮਾਟਰ",
        "crop_mr": "टोमॅटो",
        "crop_te": "టమోటా",
        "crop_ta": "தக்காளி",
        "disease": "Early Blight",
        "disease_hi": "अर्ली ब्लाइट (अगेती झुलसा)",
        "disease_pa": "ਅਗੇਤਾ ਝੁਲਸ ਰੋਗ",
        "disease_mr": "लवकर येणारा करपा",
        "disease_te": "ముందస్తు తెగులు",
        "disease_ta": "ஆரம்ப கருகல் நோய்",
        "pathogen": "Fungus (Alternaria solani)",
        "pathogen_type": "fungal",
        "description": "Characterized by brown-to-black spots with concentric rings (target board pattern) on older leaves. Can cause severe defoliation and yield loss.",
        "description_hi": "निचली पत्तियों पर गहरे भूरे रंग के छल्लेदार धब्बे बनते हैं। पत्तियां सूखकर गिरने लगती हैं।"
    },
    "Tomato___Late_blight": {
        "crop": "Tomato",
        "crop_hi": "टमाटर",
        "crop_pa": "ਟਮਾਟਰ",
        "crop_mr": "टोमॅटो",
        "crop_te": "టమోటా",
        "crop_ta": "தக்காளி",
        "disease": "Late Blight",
        "disease_hi": "लेट ब्लाइट (पछेती झुलसा)",
        "disease_pa": "ਪਛੇਤਾ ਝੁਲਸ ਰੋਗ",
        "disease_mr": "उशिरा येणारा करपा",
        "disease_te": "ఆలస్యపు తెగులు",
        "disease_ta": "தாமத கருகல் நோய்",
        "pathogen": "Oomycete (Phytophthora infestans)",
        "pathogen_type": "fungal",
        "description": "Water-soaked dark lesions spreading rapidly on foliage and stems with white mold growth in humid conditions.",
        "description_hi": "पत्तियों और तनों पर पानी से भीगे हुए गहरे धब्बे तेजी से फैलते हैं। अधिक नमी में सफेद फफूंद दिखती है।"
    },
    "Tomato___Bacterial_spot": {
        "crop": "Tomato",
        "crop_hi": "टमाटर",
        "crop_pa": "ਟਮਾਟਰ",
        "crop_mr": "टोमॅटो",
        "crop_te": "టమోటా",
        "crop_ta": "தக்காளி",
        "disease": "Bacterial Spot",
        "disease_hi": "जीवाणु धब्बा रोग",
        "disease_pa": "ਬੈਕਟੀਰੀਅਲ ਸਪਾਟ",
        "disease_mr": "जिवाणू ठिपके",
        "disease_te": "బాక్టీరియల్ మచ్చల తెగులు",
        "disease_ta": "பாக்டீரியா புள்ளி நோய்",
        "pathogen": "Bacterium (Xanthomonas spp.)",
        "pathogen_type": "bacterial",
        "description": "Small, dark, greasy or water-soaked spots with yellow halos on leaves, stems, and fruit.",
        "description_hi": "पत्तियों पर छोटे, काले, तेल जैसे धब्बे जिनके चारों ओर पीला घेरा होता है।"
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "crop": "Tomato",
        "crop_hi": "टमाटर",
        "crop_pa": "ਟਮਾਟਰ",
        "crop_mr": "टोमॅटो",
        "crop_te": "టమోటా",
        "crop_ta": "தக்காளி",
        "disease": "Yellow Leaf Curl Virus",
        "disease_hi": "पर्ण कुंचन विषाणु रोग (लीफ कर्ल)",
        "disease_pa": "ਪੱਤਾ ਮਰੋੜ ਵਿਸ਼ਾਣੂ ਰੋਗ",
        "disease_mr": "पिवळा पान आकुंचन विषाणू",
        "disease_te": "పసుపు ఆకు ముడుత తెగులు",
        "disease_ta": "மஞ்சள் இலை சுருள் வைரஸ்",
        "pathogen": "Begomovirus (transmitted by Whiteflies)",
        "pathogen_type": "viral",
        "description": "Leaves curl upwards, turn pale yellow along margins, and plant exhibits stunted growth.",
        "description_hi": "पत्तियां ऊपर की तरफ मुड़ती हैं और किनारों से पीली हो जाती हैं। पौधे का विकास रुक जाता है।"
    },
    "Tomato___healthy": {
        "crop": "Tomato",
        "crop_hi": "टमाटर",
        "crop_pa": "ਟਮਾਟਰ",
        "crop_mr": "टोमॅटो",
        "crop_te": "టమోటా",
        "crop_ta": "தக்காளி",
        "disease": "Healthy",
        "disease_hi": "स्वस्थ पौधा",
        "disease_pa": "ਤੰਦਰੁਸਤ ਪੌਦਾ",
        "disease_mr": "निरोगी वनस्पती",
        "disease_te": "ఆరోగ్యకరమైన పంట",
        "disease_ta": "ஆரோக்கியமான பயிர்",
        "pathogen": "None",
        "pathogen_type": "none",
        "description": "Foliage exhibits vigorous deep green coloration with intact cellular morphology and no signs of pathogen damage.",
        "description_hi": "पत्तियां पूरी तरह स्वस्थ, हरी और रोगमुक्त हैं।"
    },
    "Potato___Early_blight": {
        "crop": "Potato",
        "crop_hi": "आलू",
        "crop_pa": "ਆਲੂ",
        "crop_mr": "बटाटा",
        "crop_te": "బంగాళాదుంప",
        "crop_ta": "உருளைக்கிழங்கு",
        "disease": "Early Blight",
        "disease_hi": "अगेती झुलसा रोग",
        "disease_pa": "ਅਗੇਤਾ ਝੁਲਸ ਰੋਗ",
        "disease_mr": "लवकर येणारा करपा",
        "disease_te": "ముందస్తు తెగులు",
        "disease_ta": "ஆரம்ப கருகல் நோய்",
        "pathogen": "Fungus (Alternaria solani)",
        "pathogen_type": "fungal",
        "description": "Concentric rings resembling bullseye marks on lower foliage, causing premature senescence.",
        "description_hi": "निचली पत्तियों पर गोल छल्लेदार गहरे धब्बे, जिससे पत्तियां समय से पहले पीली होकर गिरती हैं।"
    },
    "Potato___Late_blight": {
        "crop": "Potato",
        "crop_hi": "आलू",
        "crop_pa": "ਆਲੂ",
        "crop_mr": "बटाटा",
        "crop_te": "బంగాళాదుంప",
        "crop_ta": "உருளைக்கிழங்கு",
        "disease": "Late Blight",
        "disease_hi": "पछेती झुलसा रोग",
        "disease_pa": "ਪਛੇਤਾ ਝੁਲਸ ਰੋਗ",
        "disease_mr": "उशिरा येणारा करपा",
        "disease_te": "ఆలస్యపు తెగులు",
        "disease_ta": "தாமத கருகல் நோய்",
        "pathogen": "Oomycete (Phytophthora infestans)",
        "pathogen_type": "fungal",
        "description": "Water-soaked irregular black necrotic spots with white cottony sporulation on the underside in damp cool weather.",
        "description_hi": "पत्तियों के निचले हिस्से पर सफेद फफूंद और काले धब्बे, जो नम और ठंडे मौसम में तेजी से फैलते हैं।"
    },
    "Potato___healthy": {
        "crop": "Potato",
        "crop_hi": "आलू",
        "crop_pa": "ਆਲੂ",
        "crop_mr": "बटाटा",
        "crop_te": "బంగాళాదుంప",
        "crop_ta": "உருளைக்கிழங்கு",
        "disease": "Healthy",
        "disease_hi": "स्वस्थ पौधा",
        "disease_pa": "ਤੰਦਰੁਸਤ ਪੌਦਾ",
        "disease_mr": "निरोगी वनस्पती",
        "disease_te": "ఆరోగ్యకరమైన పంట",
        "disease_ta": "ஆரோக்கியமான பயிர்",
        "pathogen": "None",
        "pathogen_type": "none",
        "description": "Healthy lush potato leaves with vibrant green tissue.",
        "description_hi": "आलू की पत्तियां पूरी तरह स्वस्थ और हरी हैं।"
    },
    "Corn_(maize)___Common_rust_": {
        "crop": "Corn (Maize)",
        "crop_hi": "मक्का",
        "crop_pa": "ਮੱਕੀ",
        "crop_mr": "मका",
        "crop_te": "మొక్కజొన్న",
        "crop_ta": "மக்காச்சோளம்",
        "disease": "Common Rust",
        "disease_hi": "गेरुआ / रतुआ रोग",
        "disease_pa": "ਰੱਤੂਆ ਰੋਗ",
        "disease_mr": "तांबेरा रोग",
        "disease_te": "తుప్పు తెగులు",
        "disease_ta": "துரு நோய்",
        "pathogen": "Fungus (Puccinia sorghi)",
        "pathogen_type": "fungal",
        "description": "Elongated golden-brown to cinnamon-brown pustules scattered across both upper and lower leaf surfaces.",
        "description_hi": "पत्तियों के दोनों तरफ दालचीनी या भूरे रंग के उभरे हुए फफोले (पुस्ट्यूल) बन जाते हैं।"
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "crop": "Corn (Maize)",
        "crop_hi": "मक्का",
        "crop_pa": "ਮੱਕੀ",
        "crop_mr": "मका",
        "crop_te": "మొక్కజొన్న",
        "crop_ta": "மக்காச்சோளம்",
        "disease": "Northern Leaf Blight",
        "disease_hi": "उत्तरी पत्ती झुलसा",
        "disease_pa": "ਉੱਤਰੀ ਪੱਤਾ ਝੁਲਸ",
        "disease_mr": "उत्तरी पान करपा",
        "disease_te": "ఉత్తర ఆకు తెగులు",
        "disease_ta": "வடக்கு இலை கருகல்",
        "pathogen": "Fungus (Exserohilum turcicum)",
        "pathogen_type": "fungal",
        "description": "Long, cigar-shaped grayish-green to tan lesions that run parallel to leaf margins.",
        "description_hi": "पत्तियों पर सिगार के आकार के लंबे, भूरे-हरे घाव बनते हैं जो प्रकाश संश्लेषण को रोकते हैं।"
    },
    "Corn_(maize)___healthy": {
        "crop": "Corn (Maize)",
        "crop_hi": "मक्का",
        "crop_pa": "ਮੱਕੀ",
        "crop_mr": "मका",
        "crop_te": "మొక్కజొన్న",
        "crop_ta": "மக்காச்சோளம்",
        "disease": "Healthy",
        "disease_hi": "स्वस्थ पौधा",
        "disease_pa": "ਤੰਦਰੁਸਤ ਪੌਦਾ",
        "disease_mr": "निरोगी वनस्पती",
        "disease_te": "ఆరోగ్యకరమైన పంట",
        "disease_ta": "ஆரோக்கியமான பயிர்",
        "pathogen": "None",
        "pathogen_type": "none",
        "description": "Vibrant, broad green corn leaves free from fungal lesions.",
        "description_hi": "मक्के की पत्तियां स्वस्थ और मजबूत हैं।"
    },
    "Pepper,_bell___Bacterial_spot": {
        "crop": "Bell Pepper / Chilli",
        "crop_hi": "शिमला मिर्च / मिर्च",
        "crop_pa": "ਸ਼ਿਮਲਾ ਮਿਰਚ",
        "crop_mr": "शिमला मिरची",
        "crop_te": "బెల్ పెప్పర్ / మిరప",
        "crop_ta": "குடைமிளகாய்",
        "disease": "Bacterial Spot",
        "disease_hi": "जीवाणु धब्बा रोग",
        "disease_pa": "ਬੈਕਟੀਰੀਅਲ ਸਪਾਟ",
        "disease_mr": "जिवाणू ठिपके",
        "disease_te": "బాక్టీరియల్ మచ్చల తెగులు",
        "disease_ta": "பாக்டீரியா புள்ளி நோய்",
        "pathogen": "Bacterium (Xanthomonas campestris)",
        "pathogen_type": "bacterial",
        "description": "Water-soaked lesions turning into brown, irregular spots with raised margins on foliage and fruits.",
        "description_hi": "पत्तियों पर अनियमित भूरे धब्बे जिनके किनारे उभरे होते हैं। फल खराब हो सकते हैं।"
    },
    "Pepper,_bell___healthy": {
        "crop": "Bell Pepper / Chilli",
        "crop_hi": "शिमला मिर्च / मिर्च",
        "crop_pa": "ਸ਼ਿਮਲਾ ਮਿਰਚ",
        "crop_mr": "शिमला मिरची",
        "crop_te": "బెల్ పెప్పర్ / మిరప",
        "crop_ta": "குடைமிளகாய்",
        "disease": "Healthy",
        "disease_hi": "स्वस्थ पौधा",
        "disease_pa": "ਤੰਦਰੁਸਤ ਪੌਦਾ",
        "disease_mr": "निरोगी वनस्पती",
        "disease_te": "ఆరోగ్యకరమైన పంట",
        "disease_ta": "ஆரோக்கியமான பயிர்",
        "pathogen": "None",
        "pathogen_type": "none",
        "description": "Glossy deep green bell pepper foliage free of chlorosis or necrosis.",
        "description_hi": "पौधा पूरी तरह स्वस्थ और चमकदार पत्तियों वाला है।"
    },
    "Apple___Apple_scab": {
        "crop": "Apple",
        "crop_hi": "सेब",
        "crop_pa": "ਸੇਬ",
        "crop_mr": "सफरचंद",
        "crop_te": "యాపిల్",
        "crop_ta": "ஆப்பிள்",
        "disease": "Apple Scab",
        "disease_hi": "सेब का स्कैब रोग",
        "disease_pa": "ਸੇਬ ਦਾ ਸਕੈਬ",
        "disease_mr": "सफरचंद खवले रोग",
        "disease_te": "యాపిల్ స్కాబ్",
        "disease_ta": "ஆப்பிள் வடு நோய்",
        "pathogen": "Fungus (Venturia inaequalis)",
        "pathogen_type": "fungal",
        "description": "Dull olive-green velvety spots turning brownish-black with puckered leaf tissue.",
        "description_hi": "पत्तियों पर जैतून जैसे हरे मखमली धब्बे जो बाद में काले हो जाते हैं।"
    },
    "Apple___healthy": {
        "crop": "Apple",
        "crop_hi": "सेब",
        "crop_pa": "ਸੇਬ",
        "crop_mr": "सफरचंद",
        "crop_te": "యాపిల్",
        "crop_ta": "ஆப்பிள்",
        "disease": "Healthy",
        "disease_hi": "स्वस्थ पौधा",
        "disease_pa": "ਤੰਦਰੁਸਤ ਪੌਦਾ",
        "disease_mr": "निरोगी वनस्पती",
        "disease_te": "ఆరోగ్యకరమైన పంట",
        "disease_ta": "ஆரோக்கியமான பயிர்",
        "pathogen": "None",
        "pathogen_type": "none",
        "description": "Crisp green apple leaves with no fungal lesions.",
        "description_hi": "सेब की पत्तियां पूरी तरह स्वस्थ हैं।"
    }
}

def get_class_meta(raw_class_name: str) -> dict:
    """Return metadata for a given class or a friendly parsed fallback."""
    if raw_class_name in DISEASE_METADATA:
        return DISEASE_METADATA[raw_class_name]
    
    # Generic parser for any other class in PlantVillage
    parts = raw_class_name.split("___")
    crop = parts[0].replace("_", " ").strip()
    disease = parts[1].replace("_", " ").strip() if len(parts) > 1 else "Unknown"
    is_healthy = "healthy" in disease.lower()
    
    return {
        "crop": crop,
        "crop_hi": crop,
        "crop_pa": crop,
        "crop_mr": crop,
        "crop_te": crop,
        "crop_ta": crop,
        "disease": "Healthy" if is_healthy else disease,
        "disease_hi": "स्वस्थ" if is_healthy else disease,
        "disease_pa": "ਤੰਦਰੁਸਤ" if is_healthy else disease,
        "disease_mr": "निरोगी" if is_healthy else disease,
        "disease_te": "ఆరోగ్యకరమైన" if is_healthy else disease,
        "disease_ta": "ஆரோக்கியமான" if is_healthy else disease,
        "pathogen": "None" if is_healthy else "Pathogenic Organism",
        "pathogen_type": "none" if is_healthy else "fungal",
        "description": "Healthy crop foliage." if is_healthy else f"Symptoms typical of {disease} on {crop}.",
        "description_hi": "स्वस्थ फसल।" if is_healthy else f"{crop} पर {disease} के लक्षण।"
    }
